# Generated by Django 5.2.4 on 2025-08-07 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_products', '0002_alter_machinerow_chilled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinefield',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vt_products.product'),
        ),
    ]
