# Generated by Django 5.2.4 on 2025-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_products', '0003_alter_machinefield_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
