# Generated by Django 5.2.4 on 2025-09-21 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('vt_products', '0004_alter_product_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='apikey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.apikey'),
        ),
    ]
