# Generated by Django 5.2.4 on 2026-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_products', '0005_machine_apikey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='pieces',
            new_name='pieces_bought',
        ),
        migrations.AddField(
            model_name='batch',
            name='pieces_left',
            field=models.IntegerField(default=0),
        ),
    ]
