# Generated by Django 5.2.4 on 2026-01-04 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_products', '0006_rename_pieces_batch_pieces_bought_batch_pieces_left'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possible_to_refill', models.IntegerField()),
                ('actual_refill', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_products.machinefield')),
            ],
        ),
        migrations.CreateModel(
            name='RefillProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vt_products.machine')),
            ],
        ),
    ]
