# Generated by Django 5.2.4 on 2026-01-17 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_products', '0007_refillitem_refillprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
