# Generated by Django 6.0.3 on 2026-03-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_products', '0008_purchase_completed_alter_purchase_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ean',
            field=models.CharField(default='', max_length=255),
        ),
    ]
