# Generated by Django 6.0.3 on 2026-03-07 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vt_products', '0009_product_ean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackagingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='packaging_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vt_products.productpackagingtype'),
        ),
    ]
