# Generated by Django 6.0.3 on 2026-03-07 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0005_auto_20220110_1102'),
        ('vt_products', '0010_productpackagingtype_product_packaging_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='apikey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rest_framework_api_key.apikey'),
        ),
        migrations.AlterField(
            model_name='machinefield',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vt_products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vt_products.productcategory'),
        ),
    ]
